### PR TITLE
Renamed keymap to vial

### PR DESCRIPTION
**Pull request by TweetyDaBird**
Randomly named keymaps with vial support is utterly confusing and non-standard.

Should be kept to naming 'vial'.

### CODE REVIEW

**Review by lesshonor — CHANGES_REQUESTED** [review]
#312 indicates this keymap was only intended for `preonic/rev3`, so please move it under a keymap folder for that specific revision.

Based on a quick `diff <(qmk info -kb preonic/rev3_drop -f json) <(qmk info -kb preonic/rev3 -f json)` it's probably good for `rev3` and `rev3_drop`, but it's definitely not usable on anything earlier...

**Comment by xyzz** [comment]
since it's failing to compile, it's probably best to just remove it altogether

**Comment by TweetyDaBird** [comment]
I agree, but how is that done easiest?

**Comment by lesshonor** [comment]
> since it's failing to compile, it's probably best to just remove it altogether

It compiles on `preonic/rev3`, as the original PR intended.

> I agree, but how is that done easiest?

See #376 for an example.

**Review by lesshonor — APPROVED** [review]

**Pull request merged**
