### PR TITLE
Hotdox Support

### PR DESCRIPTION
**Pull request by Smurf**
This PR adds support for the Alpacalabs Hotdox keyboard.

Due to the limited storage in the MCU on the Hotdox I did have to modify the `hotdox.c` file to add ifdefs to optionally remove backlight and RGB control. This can be re-enabled via values in `rules.mk` if other features are disabled.

I have confirmed that this configuration works as expected on my v1 Hotdox.

### CODE REVIEW

**Comment by xyzz** [comment]
the default keymap fails to build

**Comment by Smurf** [comment]
Sorry about that. I seemed to have switched BACKLIGHT_ENABLE and RGBLIGHT_ENABLE around. That's what I get for 1am commits.

I have updated the hotdox.c and vial/keymap.c files to use the BACKLIGHT_ENABLE value instead of the RGBLIGHT_ENABLE.

I have confirmed that the default keymap now builds.
```
$ make hotdox:default                                                                   
Making hotdox with keymap default

avr-gcc (Fedora 13.2.0-1.fc38) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Size before:
   text	   data	    bss	    dec	    hex	filename
      0	  24774	      0	  24774	   60c6	hotdox_default.hex

Compiling: quantum/keymap_introspection.c                                                           [OK]
Linking: .build/hotdox_default.elf                                                                  [OK]
Creating load file for flashing: .build/hotdox_default.hex                                          [OK]
Copying hotdox_default.hex to qmk_firmware folder                                                   [OK]
Checking file size of hotdox_default.hex                                                            [OK]
 * The firmware size is fine - 24774/28672 (86%, 3898 bytes free)
```

**Comment by xyzz** [comment]
why are you removing the VIA keymap and changing common files, the PR should only touch vial keymap ideally to prevent future merge conflicts

**Comment by Smurf** [comment]
> why are you removing the VIA keymap and changing common files, the PR should only touch vial keymap ideally to prevent future merge conflicts

When I created the pull request there was a list of actions to take prior to submission prefilled in the pull request description. IIRC removing the via keymap was one so I did as instructed.

I need to change common files due to the storage limitation of the mcu in the hotdox.

If it's not suitable to merge that's fine. Feel free to close.

**Pull request closed without merging**
