### PR TITLE
Add firmware for the Libra Mini

### PR DESCRIPTION
**Pull request by jakobkg**
This PR adds firmware for the Libra Mini, a 40% that comes from the manufacturer with a Via enabled firmware but no QMK sources are available for it and Via can only be used by sideloading a .json seemingly originating in the depths of the comments of a youtube video. I've made a completely from-scratch firmware for the Libra Mini in this PR.

Marked as draft PR for the moment as ~only a `vial` keymap is implemented, and~ I have yet to fully implement the joystick that this keyboard has.

### CODE REVIEW

**Comment by jakobkg** [comment]
Adding the ability to remap the analog stick by presenting it as four "virtual" keys to the user in Vial turned out not quite trivial, so I've removed those bits for now. The keyboard/keymaps are ready to use as-is, I'll come back to "stick-as-buttons" functionality later on.

**Comment by dcai** [comment]
Thanks @jakobkg, have been searching for libra mini firmware source, cannot believe it's ready for vial, great work mate!

**Comment by kaiser423** [comment]
As a manufacturer, kaiser, thank you very much for your contribution

**Comment by ZXSwire3** [comment]
Is there any progress on "stick-as-buttons" functionality? I was looking around and found [this post ](https://issueantenna.com/repo/vial-kb/vial-qmk/issues/314) it doesn't seem to be for the libra mini, but for some board called [LMJ60](https://www.zfrontier.com/app/flow/4XzBPRpGkxdK). I was looking into it, but I don't know too much about it so I thought that I'd just mention it here to see if maybe you'd be able to do something better with it.

**Comment by ChaoticAlex** [comment]
> Is there any progress on "stick-as-buttons" functionality? I was looking around and found [this post ](https://issueantenna.com/repo/vial-kb/vial-qmk/issues/314) it doesn't seem to be for the libra mini, but for some board called [LMJ60](https://www.zfrontier.com/app/flow/4XzBPRpGkxdK). I was looking into it, but I don't know too much about it so I thought that I'd just mention it here to see if maybe you'd be able to do something better with it.

In my opinion, the Libra mini original stick code is a reference to this. but after QMK Breaking Changes, the Joystick code cant building like before. I'm still trying to fix it, but it seems to be making slow progress, hopefully someone can do it together.

**Pull request merged**
