### PR TITLE
Port Keychron V1 to VIAL

### PR DESCRIPTION
**Pull request by adophoxia**
As title. (Follows the same implementation as https://github.com/vial-kb/vial-qmk/pull/327)

### CODE REVIEW

**Comment by SentientUmaru** [comment]
Can you make a version for the v1 max? apparently they're different

**Comment by adophoxia** [comment]
> Can you make a version for the v1 max? apparently they're different 

@SentientUmaru 
Elaboration required.

**Comment by mikeduminy** [comment]
I'm also curious about the firmware for the V1 Max because I've seen reports that using the V1 firmware bricks a max board

**Comment by adophoxia** [comment]
> I'm also curious about the firmware for the V1 Max because I've seen reports that using the V1 firmware bricks a max board

Curious about what? If it's asking "can I use this firmware for the V1 Max?", the answer is no because it is built differently between the two boards, so you can't use one on the other. 
@mikeduminy

**Comment by mikeduminy** [comment]
Ah I found it here - https://github.com/Keychron/qmk_firmware/tree/wireless_playground/keyboards/keychron/v1_max

**Pull request merged**
