### PR TITLE
Preonic rev1 vial

### PR DESCRIPTION
**Pull request by jimerickson**
this is a default preonic keymap.c and a vial.json for preonic rev1. also includes changes to rules.mk, readme.md, and config.h, if this pull request in not adequate tell me and i will try to properly amend it, as i am new to git. this was tested on an OLKB Preonic Revision 1.  the audio is disabled because otherwise the firmware is too large. the keys for unlock are escape (2,0) and enter (3,11).

### CODE REVIEW

**Comment by xyzz** [comment]
If it's a keymap that only works on rev1, please create it under `keyboards/preonic/rev1/keymaps/vial`

**Comment by jimerickson** [comment]
```
preonic/rev1 uses UID af133167e5bc4ef6
preonic uses UID af133167e5bc4ef6
UID af133167e5bc4ef6 duplicated: {'preonic/rev1', 'preonic'}
Error: Process completed with exit code 1.
```
is there anything i need to do to fix this? CI/build seems to be failing. my apologies if i screwed something up.

**Comment by xyzz** [comment]
It looks like you created the new `keyboards/preonic/rev1/keymaps/vial` but didn't delete the old `preonic_rev1_vial` one

**Comment by jimerickson** [comment]
oh ok so i need to delete the old branch? sorry i guess i don't understand what to do.

**Comment by jimerickson** [comment]
ok so i did a "git add --all" and "git commit" and it deleted the files. it should build now.

**Comment by edasque** [comment]
@[jimerickson](https://github.com/jimerickson) Does this work? When I try: `qmk compile -kb preonic/rev1 -km vial`, I get the following:
```
Ψ Compiling keymap with gmake --jobs=1 preonic/rev1:vial


Making preonic/rev1 with keymap vial

avr-gcc (Homebrew AVR GCC 8.4.0_2) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling: quantum/via.c                                                                           quantum/via.c:26:2: error: #error Compiling VIA keymaps is not supported with the vial-qmk repo, please use qmk_firmware instead, or set VIAL_ENABLE=yes
 #error Compiling VIA keymaps is not supported with the vial-qmk repo, please use qmk_firmware instead, or set VIAL_ENABLE=yes
  ^~~~~
 [ERRORS]
 |
 |
 |
gmake[1]: *** [builddefs/common_rules.mk:459: .build/obj_preonic_rev1_vial/quantum/via.o] Error 1
gmake: *** [Makefile:413: preonic/rev1:vial] Error 1
Make finished with errors
```

**Comment by jimerickson** [comment]
eric,
works fine for me on linux. ubuntu to be exact. did you put
ViAL_ENABLE=yes in your rules.mk?
--
Jim Erickson

**Comment by edasque** [comment]
Yes, my bad, it was an issue with not having up to date submodules.

**Comment by jimerickson** [comment]
glad you got it worked out! enjoy.
--
Jim Erickson

**Pull request merged**
