### PR TITLE
Add - chatelao/teampad

### PR DESCRIPTION
**Pull request by chatelao**
This is my little "TeamPad" a reworked Wormier k21 fitted with a XIAO RP2040.

### CODE REVIEW

**Comment by xyzz** [comment]
* vial needs to go into the vial keymap, not the default keymap
* there are a bunch of files that shouldn't be there like keymaps.zip, info.orig_small.json

**Comment by chatelao** [comment]
Thanks a lot, I will fix it and come back again.

**Comment by chatelao** [comment]
Please wait to merge, I have to fix the "README" first - mea culpa

**Comment by xyzz** [comment]
there is no update for over a month, closing

**Pull request closed without merging**
