### PR TITLE
Vial support for KBDfans KBD67

### PR DESCRIPTION
**Pull request by alkk**
Vial keymap added for KBDFans KBD67 (tested on Lite R3)

### CODE REVIEW

**Comment by xyzz** [comment]
Was this tested on v1, v2 or v3? since these are completely different hardware, you should put the keymap under a specific folder depending what it was tested on

**Comment by alkk** [comment]
You are right, it's for V3. I've moved it to correct(?) location.

**Comment by xyzz** [comment]
Looks like it's failing to compile:

```
2022-01-27T22:10:16.7751777Z Copying kbdfans_kbd67_mkiirgb_v3_vial.bin to qmk_firmware folder                                    [32;01m[OK][0m
2022-01-27T22:10:16.7908846Z Checking file size of kbdfans_kbd67_mkiirgb_v3_vial.bin                                            
2022-01-27T22:10:16.7909368Z  * [31;01mThe firmware is too large![0m 26922/26624 (298 bytes over)
2022-01-27T22:10:16.7918514Z  [31;01m[ERRORS][0m
2022-01-27T22:10:16.7921939Z 
2022-01-27T22:10:16.7923680Z make[1]: *** [tmk_core/rules.mk:490: check-size] Error 1
2022-01-27T22:10:16.7934985Z make: *** [Makefile:478: kbdfans/kbd67/mkiirgb/v3:vial] Error 1
2022-01-27T22:10:16.7935430Z [31;01mMake finished with errors
```

**Comment by alkk** [comment]
It's rather interesting, my local build was successful (I'm runnig this build right now).
The only difference I see is compiler version, I'm using avr-gcc (Homebrew AVR GCC 8.4.0_2) 8.4.0

**Comment by xyzz** [comment]
Yes, it's using qmk docker image which unfortunately comes with a very bad avr compiler version, I plan to replace it at some point but it's a lot of work.

**Pull request merged**
