### PR TITLE
Port GMMK Numpad

### PR DESCRIPTION
**Pull request by RustedAperture**
Adding support for GMMK numpad to Vial. This was tested on my devices without issue.

### CODE REVIEW

**Comment by xyzz** [comment]
- it's failing to build:
```
2023-03-09T04:47:14.8730392Z Assembling: lib/chibios/os/common/startup/ARMCMx/compilers/GCC/crt0_v7m.S                          Assembling: lib/chibios/os/common/startup/ARMCMx/compilers/GCC/vectors.S                            [31;01m[ERRORS][0m
2023-03-09T04:47:14.8847407Z make[1]: *** [builddefs/common_rules.mk:361: .build/obj_gmmk_numpad_rustedaperture/./lib/chibios/os/common/startup/ARMCMx/compilers/GCC/crt0_v7m.o] Error 1
2023-03-09T04:47:14.8847788Z  | 
2023-03-09T04:47:14.8848014Z make[1]: *** Waiting for unfinished jobs....
2023-03-09T04:47:14.8848753Z  | ./keyboards/gmmk/numpad/keymaps/rustedaperture/config.h: Assembler messages:
2023-03-09T04:47:14.8849333Z  | ./keyboards/gmmk/numpad/keymaps/rustedaperture/config.h:36: Error: bad instruction `enum custom_user_layers {'
2023-03-09T04:47:14.8850873Z  | ./keyboards/gmmk/numpad/keymaps/rustedaperture/config.h:37: Error: bad instruction `_base,'
2023-03-09T04:47:14.8854405Z  | ./keyboards/gmmk/numpad/keymaps/rustedaperture/config.h:38: Error: bad instruction `_util,'
2023-03-09T04:47:14.8855244Z  | ./keyboards/gmmk/numpad/keymaps/rustedaperture/config.h:39: Error: bad instruction `_draw1,'
2023-03-09T04:47:14.8855690Z  | ./keyboards/gmmk/numpad/keymaps/rustedaperture/config.h:40: Error: bad instruction `_draw2,'
2023-03-09T04:47:14.8856114Z  | ./keyboards/gmmk/numpad/keymaps/rustedaperture/config.h:41: Error: junk at end of line, first unrecognized character is `}'
2023-03-09T04:47:14.8856432Z  | 
2023-03-09T04:47:14.8879172Z  [32;01m[OK][0m
2023-03-09T04:47:14.8898984Z  [31;01m[ERRORS][0m
2023-03-09T04:47:14.8912732Z  | 
2023-03-09T04:47:14.8913580Z  | ./keyboards/gmmk/numpad/keymaps/rustedaperture/config.h: Assembler messages:
2023-03-09T04:47:14.8914148Z  | ./keyboards/gmmk/numpad/keymaps/rustedaperture/config.h:36: Error: bad instruction `enum custom_user_layers {'
2023-03-09T04:47:14.8914589Z  | ./keyboards/gmmk/numpad/keymaps/rustedaperture/config.h:37: Error: bad instruction `_base,'
2023-03-09T04:47:14.8915774Z  | ./keyboards/gmmk/numpad/keymaps/rustedaperture/config.h:38: Error: bad instruction `_util,'
2023-03-09T04:47:14.8916261Z  | ./keyboards/gmmk/numpad/keymaps/rustedaperture/config.h:39: Error: bad instruction `_draw1,'
2023-03-09T04:47:14.8916636Z  | ./keyboards/gmmk/numpad/keymaps/rustedaperture/config.h:40: Error: bad instruction `_draw2,'
2023-03-09T04:47:14.8917067Z  | ./keyboards/gmmk/numpad/keymaps/rustedaperture/config.h:41: Error: junk at end of line, first unrecognized character is `}'
2023-03-09T04:47:14.8917372Z  | 
2023-03-09T04:47:14.8917726Z make[1]: *** [builddefs/common_rules.mk:361: .build/obj_gmmk_numpad_rustedaperture/./lib/chibios/os/common/startup/ARMCMx/compilers/GCC/vectors.o] Error 1
2023-03-09T04:47:14.8923690Z  [32;01m[OK][0m
2023-03-09T04:47:14.8939465Z [31;01mMake finished with errors
2023-03-09T04:47:14.8940874Z make: *** [Makefile:414: gmmk/numpad:rustedaperture] Error 1
```
- if you are opening a PR to qmk, please wait for them to merge your keyboard before opening another PR to vial-qmk, in order to avoid future conflicts

**Comment by RustedAperture** [comment]
@xyzz Apologies I merged my local keymap, I wasn't meant to do that. explains why it failed. I will hold on this until I get the other merged.

**Comment by xyzz** [comment]
> I will hold on this until I get the other merged.

okay, in this case I'll convert it to draft and you can change back and leave a comment once it's ready

**Comment by RustedAperture** [comment]
> > I will hold on this until I get the other merged.
> 
> okay, in this case I'll convert it to draft and you can change back and leave a comment once it's ready

Thank you, I did notice that the vial branch is missing some code from chibios. My default keymap builds fine in the qmk_firmware official but I get lots of errors here on vial. Seems support for WB32 ADC is missing from analog.c

**Pull request closed without merging**
