### PR TITLE
Adding mario keyboard

### PR DESCRIPTION
**Pull request by ykiewang**
Adding a keyboard named mario, which has a encoder in the left half and a joystick in the right half.

### CODE REVIEW

**Comment by xyzz** [comment]
failing to build due to duplicate uid

**Comment by ykiewang** [comment]
> failing to build due to duplicate uid

I have revised it, thanks.

**Comment by xyzz** [comment]
still failing to build

**Comment by ykiewang** [comment]
> still failing to build

I have fixed it, many thanks!

This is my first time uploading a keymap, and I encountered a few issues that resulted in a building failure. I've documented the problems I faced and the solutions I found to help others who might need it.

Add default keymap: Make sure you have a default keymap, because the first step in the workflow is to compile your default keymap.

Enable Actions on Your Cloned Branch: Make sure to enable GitHub Actions on your cloned branch. This way, every time you commit code, the workflow will automatically execute, allowing you to see the results and understand the causes of any issues.

Firmware Size Limit: The firmware size can easily exceed the maximum allowed size. To mitigate this, you can disable RGB features and other unnecessary functionalities.

**Pull request merged**
