### PR TITLE
ported FancyCustoms Alicia/Aletheia to vial

### PR DESCRIPTION
**Pull request by jcshumpert**
Porting vial to FancyCustoms Aletheia/Alicia keyboard:
https://fancycustoms.com/products/alicia

### CODE REVIEW

**Comment by xyzz** [comment]
it's failing to build

**Comment by jcshumpert** [comment]
Is there a way to force it to try another build? It compiled just fine on my pc and flashed to the board no problem.

I tried pulling down my branch to another pc and it also compiled there.

image

Looking at the output of the compile in git it looks like it was compiling for a different board/PR:
image
That Ilumkb board wasn't part of my PR.

**Comment by xyzz** [comment]
here's the actual error message:

```
2023-02-06T11:10:00.0977542Z ==> Compiling fancy_customs/aletheia:vial
2023-02-06T11:10:00.9822336Z Making [1mfancy_customs/aletheia[0m with keymap [1mvial[0m
2023-02-06T11:10:00.9823025Z 
2023-02-06T11:10:01.9399870Z avr-gcc (GCC) 8.3.0
2023-02-06T11:10:01.9400246Z Copyright (C) 2018 Free Software Foundation, Inc.
2023-02-06T11:10:01.9400578Z This is free software; see the source for copying conditions.  There is NO
2023-02-06T11:10:01.9400960Z warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
2023-02-06T11:10:01.9401168Z 
2023-02-06T11:10:02.4692104Z Generating: .build/obj_fancy_customs_aletheia/src/info_config.h                                    Generating: .build/obj_fancy_customs_aletheia/src/default_keyboard.c                               Generating: .build/obj_fancy_customs_aletheia/src/default_keyboard.h                               Generating: .build/obj_fancy_customs_aletheia/src/layouts.h                                         [32;01m[OK][0m
2023-02-06T11:10:02.4784584Z  [32;01m[OK][0m
2023-02-06T11:10:02.4790163Z  [32;01m[OK][0m
2023-02-06T11:10:02.4897107Z  [32;01m[OK][0m
2023-02-06T11:10:02.5126134Z [01m[Kkeyboards/fancy_customs/aletheia/aletheia.c:17:10:[m[K [01;31m[Kfatal error: [m[KAletheia.h: No such file or directory
2023-02-06T11:10:02.5126569Z  #include [01;31m[K"Aletheia.h"[m[K
2023-02-06T11:10:02.5126858Z           [01;31m[K^~~~~~~~~~~~[m[K
2023-02-06T11:10:02.5127068Z compilation terminated.
2023-02-06T11:10:02.5283213Z Compiling: keyboards/fancy_customs/aletheia/aletheia.c                                             Compiling: quantum/keymap_introspection.c                                                          Compiling: .build/obj_fancy_customs_aletheia/src/default_keyboard.c                                 [31;01m[ERRORS][0m
2023-02-06T11:10:02.5335472Z  | 
2023-02-06T11:10:02.5335679Z  | 
2023-02-06T11:10:02.5335827Z  | 
2023-02-06T11:10:02.5362403Z make[1]: *** [builddefs/common_rules.mk:359: .build/obj_fancy_customs_aletheia_vial/keyboards/fancy_customs/aletheia/aletheia.o] Error 1
2023-02-06T11:10:02.5362790Z make[1]: *** Waiting for unfinished jobs....
2023-02-06T11:10:02.5516388Z Compiling: quantum/quantum.c                                                                        [32;01m[OK][0m
2023-02-06T11:10:02.5565407Z  [32;01m[OK][0m
2023-02-06T11:10:02.5963678Z  [32;01m[OK][0m
2023-02-06T11:10:02.5977037Z make: *** [Makefile:414: fancy_customs/aletheia:vial] Error 1
2023-02-06T11:10:02.5980447Z [31;01mMake finished with errors
```

**Comment by jcshumpert** [comment]
> here's the actual error message:
> 
> ```
> 2023-02-06T11:10:00.0977542Z ==> Compiling fancy_customs/aletheia:vial
> 2023-02-06T11:10:00.9822336Z Making �[1mfancy_customs/aletheia�[0m with keymap �[1mvial�[0m
> 2023-02-06T11:10:00.9823025Z 
> 2023-02-06T11:10:01.9399870Z avr-gcc (GCC) 8.3.0
> 2023-02-06T11:10:01.9400246Z Copyright (C) 2018 Free Software Foundation, Inc.
> 2023-02-06T11:10:01.9400578Z This is free software; see the source for copying conditions.  There is NO
> 2023-02-06T11:10:01.9400960Z warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 2023-02-06T11:10:01.9401168Z 
> 2023-02-06T11:10:02.4692104Z Generating: .build/obj_fancy_customs_aletheia/src/info_config.h                                    Generating: .build/obj_fancy_customs_aletheia/src/default_keyboard.c                               Generating: .build/obj_fancy_customs_aletheia/src/default_keyboard.h                               Generating: .build/obj_fancy_customs_aletheia/src/layouts.h                                         �[32;01m[OK]�[0m
> 2023-02-06T11:10:02.4784584Z  �[32;01m[OK]�[0m
> 2023-02-06T11:10:02.4790163Z  �[32;01m[OK]�[0m
> 2023-02-06T11:10:02.4897107Z  �[32;01m[OK]�[0m
> 2023-02-06T11:10:02.5126134Z �[01m�[Kkeyboards/fancy_customs/aletheia/aletheia.c:17:10:�[m�[K �[01;31m�[Kfatal error: �[m�[KAletheia.h: No such file or directory
> 2023-02-06T11:10:02.5126569Z  #include �[01;31m�[K"Aletheia.h"�[m�[K
> 2023-02-06T11:10:02.5126858Z           �[01;31m�[K^~~~~~~~~~~~�[m�[K
> 2023-02-06T11:10:02.5127068Z compilation terminated.
> 2023-02-06T11:10:02.5283213Z Compiling: keyboards/fancy_customs/aletheia/aletheia.c                                             Compiling: quantum/keymap_introspection.c                                                          Compiling: .build/obj_fancy_customs_aletheia/src/default_keyboard.c                                 �[31;01m[ERRORS]�[0m
> 2023-02-06T11:10:02.5335472Z  | 
> 2023-02-06T11:10:02.5335679Z  | 
> 2023-02-06T11:10:02.5335827Z  | 
> 2023-02-06T11:10:02.5362403Z make[1]: *** [builddefs/common_rules.mk:359: .build/obj_fancy_customs_aletheia_vial/keyboards/fancy_customs/aletheia/aletheia.o] Error 1
> 2023-02-06T11:10:02.5362790Z make[1]: *** Waiting for unfinished jobs....
> 2023-02-06T11:10:02.5516388Z Compiling: quantum/quantum.c                                                                        �[32;01m[OK]�[0m
> 2023-02-06T11:10:02.5565407Z  �[32;01m[OK]�[0m
> 2023-02-06T11:10:02.5963678Z  �[32;01m[OK]�[0m
> 2023-02-06T11:10:02.5977037Z make: *** [Makefile:414: fancy_customs/aletheia:vial] Error 1
> 2023-02-06T11:10:02.5980447Z �[31;01mMake finished with errors
> ```

Thank you. That helps. I think I found the issue. Looks like the include statement had different casing (Aletheia.h) vs the actual file name (aletheia.h). I guess QMK MSYS isn't case sensitive on windows since I didn't have issues on my end. Thanks again.

**Pull request merged**
