### PR TITLE
Add vial support the murcielago

### PR DESCRIPTION
**Pull request by tomsquest**
The Murcielago  is already supported in Qmk and Via.

- `vial.json` taken from https://github.com/the-via/keyboards/blob/master/src/elagil/murcielago/murcielago.json
- `LTO_ENABLE = yes` added to reduce the size (~97% with the option, so required).

Pinging @elagil, the creator, for info :star2:

### CODE REVIEW

**Comment by xyzz** [comment]
it's failing to build due to missing secure unlock configuration, can you fix this?

**Comment by tomsquest** [comment]
Hi @xyzz ,

I added these VIAL_UNLOCK lines:

```
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}
```

But, I am unsure of those keys. I searched the repo, and found many different key combinations. I don't know how I can find the right column/row IDs for the Murcielago.

**Comment by xyzz** [comment]
See https://get.vial.today/docs/porting-to-vial.html#6-set-up-a-secure-unlock-combination

**Comment by elagil** [comment]
Very nice, I wasn't even aware of Vial! Thanks for porting it over.

**Comment by tomsquest** [comment]
Hi @xyzz ,

Changed the combo keys to the two thumb keys, according to the matrix in `keymap.c`.

**Pull request merged**
