### PR TITLE
My new macropad

### PR DESCRIPTION
**Pull request by Ll3ma**
its my new macropad called The PASSWORD my keymap is called vial and i will be releasing most of the details soon

### CODE REVIEW

**Comment by xyzz** [comment]
please add a "default" keymap so that the build can pass

**Comment by Ll3ma** [comment]
> please add a "default" keymap so that the build can pass

fixed

**Comment by xyzz** [comment]
there should be two keymaps, the "default" keymaps shouldn't have via or vial enabled, and the "vial" keymaps should have it enabled

**Comment by Ll3ma** [comment]
fixed

**Pull request merged**
