### PR TITLE
fixing stuff

### PR DESCRIPTION
**Pull request by Ll3ma**
just moving stuff to ll3macorn folder and adding stuff such as readme also editing some of the files of my boards

### CODE REVIEW

**Comment by Ll3ma** [comment]
Uh

**Comment by xyzz** [comment]
why are there changes not related to adding the vial keymap?

**Comment by Ll3ma** [comment]
What do you mean?

**Comment by xyzz** [comment]
There are conflicts here can you rebase on latest vial branch

**Pull request closed without merging**
